// DO NOT EDIT. This file is generated by package:intl_translation.

// This is a library that looks up messages for specific locales by delegating
// to the appropriate library.

export 'app_messages_all_locales.dart' show initializeMessages;
