// DO NOT EDIT. This file is generated by package:intl_translation.

// This is a library that provides messages for a fr locale. All the messages
// from the main program should be duplicated here with the same function name.

// ignore_for_file: type=lint, unused_import

import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

final MessageLookup messages = MessageLookup();


class MessageLookup extends MessageLookupByLibrary {
  @override
  String get localeName => 'fr';

  @override
  final Map<String, dynamic> messages = _notInlinedMessages(_notInlinedMessages);

  static Map<String, dynamic> _notInlinedMessages(_) => {
    'Hello from application': MessageLookupByLibrary.simpleMessage('Bonjour de l\'application'),
  };
}
