// DO NOT EDIT. This file is generated by package:intl_translation.

// This is a library that provides messages for a fr_xyz123 locale. All the messages
// from the main program should be duplicated here with the same function name.

// ignore_for_file: directives_ordering
// ignore_for_file: file_names
// ignore_for_file: invalid_assignment
// ignore_for_file: unnecessary_brace_in_string_interps
// ignore_for_file: unused_import

import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';

final MessageLookup messages = MessageLookup();


class MessageLookup extends MessageLookupByLibrary {
  @override
  String get localeName => 'fr_xyz123';

  @override
  final Map<String, dynamic> messages = _notInlinedMessages(_notInlinedMessages);

  static Map<String, dynamic> _notInlinedMessages(_) => {
    'Hello from component': MessageLookupByLibrary.simpleMessage('Bonjour du composant'),
    '_message2': MessageLookupByLibrary.simpleMessage('Locale explicite'),
  };
}
